.github/workflows/release.yml, proto/content.proto
- Use int32 for asset index, @bobaaaaa 
- add `publication_date` to Metadata object
=> Assetindex + publication_date

.gitignore, Makefile, stroeer/article/v1/service.proto, stroeer/core/v1/article.proto, stroeer/section/v1/service.proto
`make LANGUAGE=go OUTPUT=./go`
no ci or module management so far
=> generate go code

all-core.proto, all-web.proto, buf.yaml
to make them work again with tools like bloomrpc
=> split all.proto

Dockerfile
=> add dockerfile for `stroeer/protoc-dockerized`

README.md, build_docker.sh
add missing files and docu for docker release process to docker hub
=> doku and script for docker release

Makefile
fix: changed Docker image reference to GHCR reference
=> bugfix / reference to docker image

.github/workflows/docker-release.yml
Added a Github action workflow to build and publish the `protoc` Docker image when changes to it occurred.
feature: added Github action to release internally used Docker image on push to master to GHCR.
=> feature / docker release action

node/__tests__/services.test.ts
Testing the new page based services.
=> fix(node): update tests

.gitignore, all-core.proto, all-coremedia.proto, all-pages.proto, all-web.proto, buf.yaml
• remove redundant `all-*.proto` files
• maintain `.gitignore` file
=> [chore] delete all-*.proto files and maintain gitignore

stroeer/coremedia/v1/curated_stage.proto, stroeer/coremedia/v1/curation_service.proto
- use C-style comments
- add service method to fetch all possible `stage_id` to `numeric list id` mappings
=> [coremedia] Update message comments

stroeer/core/v1/article.proto
@thisismana @bobaaaaa @harryurban @FalkoBasner in addition to the review of the docs we should also talk about the TODOs in the PR.
=> Documented core.Article proto messages

node/package-lock.json, node/package.json
Bumped all dependencies except the protobuf 3.14 release
=> chore(node): dependencies

stroeer/core/v1/article.proto
this should be part of a breaking change release since I reordered the proto indices
fixes #115
=> removed deprecated index of Assets

stroeer/core/v1/article.proto
=> use an enum for the state of an article

Makefile
=> new protoc image with latest dependencies using protoc 3.14.0

node/package-lock.json, node/package.json
- fixed "potential security vulnerabilities"
- updated dependencies
=> chore(node): version bump

stroeer/core/v1/article.proto
- (💥) delete unused `ELEMENT_RELATION_INLINE`
- removed TODOs and updated the docs
=> Refactoring: element relations

stroeer/core/v1/article.proto
From the FE perspective we only need two dates:
* publication date
* updated (Aktualisiert am)
Let's discuss!
=> Refactoring: Timestamps

stroeer/page/section/v1/section_page.proto
Oh snap!
Will release `0.13.1` even this is breaking.
=> fix: non repeated sections

node/README.md, node/package-lock.json, node/package.json, node/tsconfig.json
Version bumps incl. security update.
ℹ️ protoc 3.17 is now available
=> chore(node): security updates

stroeer/core/v1/core_article_service.proto, stroeer/page/section/v1/section_page_service.proto
- allow page based paging for the SectionPageService
- allow  token based paging for the ArticleService
- either again page based
- or rpc streaming (experimental)
Resources to consider:
- https://google.aip.dev/158 
> The response must not be a streaming response.
=> draft: pagination

stroeer/core/v1/article.proto
also updated docs to be more google-like, like [this one](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#syntax)
=> Added ContentType `EXTERNAL`

node-legacy/__tests__/services.test.ts, node-legacy/package-lock.json, node-legacy/package.json, node/__tests__/services.test.ts, node/package-lock.json, node/package.json
=> chore(node): version bumps

stroeer/core/v1/article.proto
add field `score` to Keyword message for https://github.com/stroeer/el-dub-tor/pull/463
=> add score to Keyword message

stroeer/core/v1/article.proto
=> add new subtype from marker "Quiz"

stroeer/core/v1/article.proto
✅ `make check`
Added new Article.SubType "COMPLIANCE" for articles like contact forms, the imprint or other legal stuff.
BUZZ-3006
=> feat: new Article.SubType "COMPLIANCE"

.gitignore
=> feat: ignore kreya config folder

node-legacy/__tests__/services.test.ts, node-legacy/package-lock.json, node-legacy/package.json, node-legacy/tsconfig.json, node/__tests__/services.test.ts, node/package-lock.json, node/package.json, node/tsconfig.json
- jest major update (with breaking changes)
- still no performance improvements in `@grpc/grpc-js` for us
=> chore: node and node-legacy

stroeer/core/v1/article.proto
- added new `EventSource`
- added `publication_id`
=> Metadata bump

.github/workflows/pr-title.yaml
=> ci: validate conventional commit PR title

node-legacy/package-lock.json, node-legacy/package.json, node/package-lock.json, node/package.json
=> chore(node|node-legacy): dependency updates

stroeer/page/section/v1/section_page.proto
=> bugfix(navigation_menu): move to section page to have consistent page

.github/workflows/pull-request.yml, Makefile, buf.gen.go.yaml, buf.gen.yaml
introduced so we can use remote plugins w/o local installation of typescript protoc plugin
=> feat: buf generate template for go

Makefile, stroeer/core/v1/article.proto
~> [BUZZ-4005](https://t-online.atlassian.net/browse/BUZZ-4005)
=> feat: added new sub_type "recipe"

README.md
Documented usage of `buf cli` and buf schema registry
=> docs: versioning, buf cli and bsr

node-proto/package-lock.json, node-proto/package.json
except `@bufbuild/protobuf` 2.x
=> chore(node-buf): latest dependencies

node-proto/package-lock.json, node-proto/package.json
=> chore(node-proto): latest versions

stroeer/page/article/v1/article_extender_service.proto
non-breaking add of field `source_ids` field to GetAnswerResponse
=> feat: non-breaking add of source_ids field to GetAnswerResponse

.github/workflows/pr-title.yaml
- non-verified: `amannn/action-semantic-pull-request` [GitHub Repo](https://github.com/amannn/action-semantic-pull-request), [GitHub Marketplace](https://github.com/marketplace/actions/semantic-pull-request)
- verified: `bufbuild/buf-action` [GitHub Repo](https://github.com/bufbuild/buf-action), [GitHub Marketplace](https://github.com/marketplace/actions/buf-action)
security
=> chore(ci): pin action

stroeer/core/v1/article.proto
- add new core.Article.Type `TOPIC` for config & content article
- add new core.Article.Body.Type `COMPANION`
```
{
"id": 10003243,
"subType": "",
"type": "TOPIC",
"bodies": [
{
"type": "BODY",
"children": [
{
"type": "",
"text": "",
"fields": {},
"children": [ { Elon Musk ist ein südafrikanisch-kanadisch-amerikanischer, vornehmlich in den ... } ],
"elements": []
}
]
},
{
"type": "COMPANION",
"children": [
{
"type": "",
"text": "",
"fields": {},
"children": [ { Zur Person   🏞️    | TABLE | TABLE |  } ],
"elements": []
}
]
}
]
}
```
=> feat: themenseiten 2.0

.github/workflows/proto.yaml
=> fix(ci): permissions
