.github/workflows/release.yml
.gitignore
Makefile
java/build.gradle
java/src/main/java/de/stroeer/api/config/ProtobufSerializer.java
java/src/test/de/stroeer/v1/article/ArticleTest.java

WHY:
`make clean` deleted source code that should have been bundled in the jar

Split generated from source code files

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
Makefile
README.md
install_proto.sh
node/package-lock.json
node/package.json

- Add Dockerfile that works for node and java
- Use docker image from Dockerfile for make
- fix paths in Makefile for always running in docker
TODO:
- publish docker image on hub.docker.com e.g. to use it
- clean package.json from obsolete dependencies

Build in Dockerfile that works for java and node

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
node/package-lock.json
node/package.json

- fixing security vulnerability in dependencies
- replace `npm install` with `npm ci` -- results in faster installs

chore(node): version bump

---

stroeer/core/v1/article.proto
stroeer/web/article/v1/web_article.proto
stroeer/web/article/v1/web_article_service.proto

Another approach on stroeer/rfb#8
Concepts:
- body is self contained and there are no references outside its scope required to render it
- allow recursion (see example `ul>li`)
- we suggest embedding complex entities (inline-articles, inline-videos, inline-galleries, ...) as `elements` where the are required. Use this for teasers and rich `<a>` with "hover effect"
- the body is a `repeated` element which would allow splitting a long story or newsticker into multiple pages (`/$article/page-1`, `/$article/page-2`) to increase PIs and AIs (Martin likes the idea 🤑)
- since the body is self contained, it may be missing when the article is used as a "trail\"
Sample structure would look like this
```id: "$ARTICLE_ID"
body {
children {
type: HTML_NODE_TYPE_PARAGRAPH
text: "Hello, world! This is …
```

Draft for self contained body

---

README.md
build_docker.sh

Manually built and published docker image to Github Container Registry (GHCR).
Replaced docker hub urls with GHCR urls in build script.
Updated docs accordingly in `Readme.md`.
feature: replaced Docker Hub image URL with Github Container Registry (GHCR) image url
refactor: added newline to end of Shell script to build docker image
docs: updated URL to Docker image
docs: updated requirements for docker image creation and release

feature / GHCR

---

buf.yaml
stroeer/web/section/v1/web_section_page.proto
stroeer/web/section/v1/web_section_service.proto

- breaking change v1?
- add v2 ?
- additive v1?
**-> Apps will use API much later -> lets to breaking change**
- e.g. GetWebSectionPageRequest, GetWebSectionPageResponse
- **buf linter says NO**
-> will be resolved by breaking change
**-> accept buf rules to only respond with object wrappers to support later adding of new fields like metadata (paging information e.g.)**
- replace Container message with recursive TeaserStage message
- TeaserStage itself would have field `repeated TeaserStage teaser_stages = 1;`
**-> agreed on ✅ **
- remember that protobuf does not support Inheritance, so the more subtypes we want to support with one message definition, the more fields exist that are only relevant for some subtypes
- **`ApiStageConfiguration`**
- currently the headline for a TeaserStage is …

BUZZ-320: WebSectionPage API

---

node/package-lock.json
node/package.json

I guess this is not critical at all but I like to align this versions together.
See #119

chore(node): bump dependencies for protoc 3.14.0

---

stroeer/page/section/v1/section_page.proto

- adapt `STAGE_ITEM_WIDTH`s to changed designs
- FULL_PAGE (no gutter was killed)
- fix some field comments

Widths for changed designs

---

stroeer/core/v1/article.proto
stroeer/core/v1/shared.proto
stroeer/page/section/v1/section_page.proto

Introducing a new message type for `SectionPage` to access all kind data to render a page's meta data or shared content. This message type contains the same data as the `Article` message. For this reason I renamed the message type `Section` to `SectionTree` to align the page field wordings.
```proto
// only for clarification:
message Article {
References references = ?;
SectionTree section_tree = ?;
// ... more 
}
message Section {
References references = ?;
SectionTree section_tree = ?;
// ... more 
}
message ArticlePage {
Article article = 1;
// ... more 
}
message SectionPage {
Section section = 1;
// ... more 
}
```
fixes #149

feat(model): shared page data

---

.github/workflows/pull-request.yml
Makefile

Added https://linter.aip.dev/ to makefile and PR workflow using default rules.
This results in something like this
```
2021/02/24 15:29:44 found problems during linting
+------------------------------------+------------------+----------------+
|                RULE                | TOTAL VIOLATIONS | VIOLATED FILES |
+------------------------------------+------------------+----------------+
| core::0140::abbreviations          |                2 |              1 |
| core::0131::response-message-name  |                3 |              3 |
| core::0131::request-name-required  |                4 |              4 |
| core::0127::http-annotation        |                4 |              4 |
| core::0131::request-unknown-fields |                4 |              4 |
| core::0131::method-signature …
```

PoC: use Google API linter on GH

---

.github/CODEOWNERS
.github/workflows/packages.yml
.github/workflows/pull-request.yml
java/build.gradle
java/gradle.properties

Created a new workflow based on Git tags with a go modules compatible scheme (`vX.X.X`). Version of java and node packages still use the identifier without the `v`.
Examples: a new tag with `v0.0.1` should release `de.stroeer.api.grpc.tapir-v1:0.0.1` for java
After this we should improve automatic releases based on tags in https://github.com/stroeer/tapir/issues/57

gh release worklow based on tags

---

.github/workflows/pull-request.yml
Makefile
README.md

- new make target to generate all source code (`make generate`) while keeping the possibility to generate only for a specific language
- new make target to test generated source code: `make test`
- integrated buf lint and breaking change detection into make
- reworked publication of protoc docker image
- new make target to release client libraries: `make release`
- check up-to-date go code generation in PR workflow
- documented all changes

Enhanced release process

---

stroeer/core/v1/article.proto

- include `Keyword` message from new keyword extraction system in `core.Article`
- re-used the existing field number since those keywords are meant to be used in the future (breaking change)
- deprecated old `entities` as a new field

feat/keywords: include extracted keywords in core.Article

---

stroeer/core/v1/core_article_service.proto
stroeer/fragment/v1/stage_service.proto
stroeer/page/article/v1/article_page_service.proto
stroeer/page/section/v1/section_page_service.proto

- added new endpoints that should allow other teams to efficiently crawl our data
- make use of the multiple GSI we currently offer, including `type` and `sub_type` filters
- added some documentation for the core service
see [BUZZ-1035](https://jira.hadcs.de/browse/BUZZ-1035)

Improve CoreArticleService

---

.gitignore
node-legacy/package.json
node-legacy/src/client.ts
node-legacy/src/server.ts
node-legacy/tsconfig.client.json
node-legacy/tsconfig.json
node/package.json
node/src/client.ts
node/src/server.ts
node/tsconfig.client.json
node/tsconfig.json

Simple http server based on the particular grpc package. Local timings:
```
@grpc/grpc-js: ~900ms
grpc: ~300ms
```

feat(node): test clients

---

stroeer/core/v1/article.proto

This is the only inconsistency of our naming (related to elements).
Affected services:
Needs to refresh the whole content: :white_check_mark:

feat(api): rename BodyNode.img to BodyNode.image

---

stroeer/core/v1/article.proto
stroeer/page/section/v1/section_page.proto

It is still not clear if we need to support AMP. Paper already removed the `ref_amp` properties completely. This might be a breaking change, because `ref_amp` is mandatory.
Affected services:
Needs to refresh the whole content: :x:

feat(api): remove amp

---

stroeer/page/article/v1/article_page.proto

RelatedArticle: replace field `source` of type enum with field `related_article_source` of type string
https://t-online.atlassian.net/browse/BUZZ-3688
https://t-online.atlassian.net/browse/BUZZ-3700

feat: add RelatedArticle source as string

---

node-proto/examples/protobuf-es/client.ts

feat(node-proto): add example with fromBinary()

---

stroeer/core/v1/article.proto

- Idee ist hier, die (named) Varianten direkt mit auszuliefern.
- Der core Article selbst bleibt unberührt, nichts ändert sich
- Wenn man eine Variante rendern soll, nimmt man z.B. je nach `field` verschiedene "Algorithmen" zum mergen des core articles mit der Variante .. in Java sähe es etwa os aus: `article.toBuilder().mergeFrom(variant)`. Bei Elementen muss man es etwas anders machen, ... Details später :)

feat: variants for ab testing articles

---

stroeer/page/article/v1/article_page.proto

chore: remove deprecated field related_articles from ArticlePage
this field was already replaced and consumers paper and paper-95 are migrated

chore: remove deprecated field `related_articles` from ArticlePage

---

stroeer/core/v1/article.proto

Introduced new field `Article.tenant` that indicates if this content belongs to a certain `tenant`.
Initially, this wll be used for regional content.

feat(core): introduce `tenant`

---

.github/workflows/packages.yml
.github/workflows/pull-request.yml
Makefile

Push tapir on release to the (public) [buf schema registry](https://buf.build/stroeer/tapir) of tapir.
see https://buf.build/docs/bsr/introduction#bsr-goals for details
✅ automatic documentation, we could remove duplications for funcdoc and simplify tools, see https://buf.build/stroeer/tapir
✅ automatic generation of client SDKs for various proto/grpc versions and languages like java, TypeScript, Go, Swift and Python - we could remove our tooling around packaging and hosting SDKs
🟡 might be free (see [plans](https://buf.build/pricing)), according to ` buf beta price` it would cost $34.00/month for Teams plan which doesn't add much value
🟡 we would need to refactor our imports in the client projects to the buf naming conventions, see examples for …

feat: push tapir to Buf schema registry for each new tag

---

stroeer/core/v1/article.proto

With references becoming an integral part of our multi-tenant API, we need separate messages to properly model stuff like:
- multi tenant domains
- relative paths
- absolute paths
- link attributes (`rel`, `target`, ..)

feat: add structured references

---

stroeer/page/section/v1/section_page.proto

`Section.references` is the counterpart of `Article.references`, but for sections. See #579.
Restructuring references at scale aka "Verlinkung 2.0"

feat: add structured section references

---

stroeer/core/v1/article.proto
stroeer/page/article/v1/article_extender_service.proto

- added a new `Body` type `ARTICLE_EXTENDER`
- `BodyNode` type is just a `string` -- using `question` for filtering
- add new `ArticleExtenderServer` method/function to receive answers for a question
- deprecated `TRUST_BOX` (already deleted in cms, adapter, frontend)
```json
{
"children": [
{
"children": [],
"elements": [],
"fields": {},
"type": "question",
"text": "Was hilft gegen Ungeziefer im Garten?",
"reference": null
},
],
"type": "ARTICLE_EXTENDER"
}
```

feat: article extender question/answer models + service

---

stroeer/page/article/v1/article_extender_service.proto

we need the article id, so that the LLM answer does not include the current article

feat: add original article id to article_extender_service.proto

---

stroeer/page/article/v1/article_extender_service.proto

- Add field `question_source` to GetAnswerRequest to be able to treat user questions differently, e.g. with a different prompt (AE-100)
- Add field `accept` to GetAnswerRequest, because we want to add markdown formatting for the answer text (AE-67)

feat: add fields `question_source` and `accept` to GetAnswerRequest

---

stroeer/core/v1/article.proto

~> support one or more WebVTT assets per video element.
```json
{
"type": "WEB_VTT",
"fields" : {
"url": "https://videos.t-online.de/2022/12/E2gC8s1n4W7j/web_vtt/subtitles_de.vtt",
"lang": "de",
"label": "Deutsch"
}
}
```

feat: added WebVTT as new Asset.Type
